# Generated by Django 4.2.1 on 2023-05-10 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favamealapi', '0002_restaurant_user_favorite_alter_favoritemeal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='user_rating',
            field=models.ManyToManyField(related_name='rated_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
