# Generated by Django 4.2.1 on 2023-05-10 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favamealapi', '0003_meal_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='meal',
            name='user_favorite',
            field=models.ManyToManyField(related_name='favorited_meakl', to=settings.AUTH_USER_MODEL),
        ),
    ]
